### DISCUSSION TITLE
Pre-built native libraries and jar dependency

### DISCUSSION THREAD

**Discussion by Aldoukfm** [skiptools/skip#183] [Q&A]
Is there a way to add local [pre-built native libraries](https://developer.android.com/studio/projects/gradle-external-native-builds#jniLibs) to /jniLibs and local [jar dependencies](https://developer.android.com/studio/projects/android-library#psd-add-aar-jar-dependency) for the Kotlin side? The swift side is implemented normally and Kotlin side use // SKIP extern handled by the pre-built library.

I've tried configuring them in the skip.yml, manually inserting my libs folder in the generated output folder of the module and re-run the project.
```yml
build:
  contents:
    - block: 'android'
      contents:
        - block: 'sourceSets'
          contents:
            - block: 'named("main")'
              contents:
                - 'jniLibs.srcDirs("libs")'
    - block: 'dependencies'
      contents:
        - 'implementation(fileTree(mapOf("dir" to "libs", "include" to listOf("*.jar"))))'
```

When I call
```swift
#if SKIP
System.loadLibrary("HelloWorldJNI")
#endif
```
inside the module, it fails with `java.lang.UnsatisfiedLinkError: dlopen failed: library "libHelloWorldJNI.so" not found`.
