### ISSUE TITLE
Kotlin 2.0 Error: Property must be initialized

### ISSUE THREAD

**Issue by marcprux** [skiptools/skip#129]
When trying to upgrade to the Kotlin 2.0 compiler (by setting `'version("kotlin", "2.0.0")'` in `SkipUnit/Skip/skip.yml`), we get a compile error with struct vars: "Property must be initialized." This is due to what as previously marked as a warning (which we had been ignoring) now becoming a full compile error: https://youtrack.jetbrains.com/issue/KT-58589

```log
GRADLE> w: CoreGraphics.kt:64:5 Property must be initialized. This warning will become an error in future releases.
```

An example of a failing type is:

```swift
public struct CGPoint: Hashable {
    public var x: Double
    public var y: Double

    public init(x: Double = 0.0, y: Double = 0.0) {
        self.x = x
        self.y = y
    }
}
```

The resulting class will exhibit the failure:

```kotlin
class CGPoint: MutableStruct {
    var x: Double
        set(newValue) {
            willmutate()
            field = newValue
            didmutate()
        }
    var y: Double
        set(newValue) {
            willmutate()
            field = newValue
            didmutate()
        }

    constructor(x: Double = 0.0, y: Double = 0.0) {
        this.x = x
        this.y = y
    }

   …
}
```

![Screenshot 2024-05-24 at 09 34 07](https://github.com/skiptools/skip/assets/659086/d895efa5-c9f6-476c-8533-c9f17ff7012f)

We cannot work around this with `lateinit`, as that raises errors "'lateinit' modifier 'is not allowed on properties of primitive types'." and "'lateinit' modifier 'is not allowed on properties with a custom getter or setter'."

We could implement default values for primitives, but non-primitives types would need some value.

Another potential solution might have been to have a bogus initializer value using a stub that just throws an error, because experimentation shows that the `_uninitialized()` stub will be called even when the constructor is used (thereby raising an error at runtime):

```kotlin
fun <T> _uninitialized(): T { error("uninitialized variable") }

class CGPoint: MutableStruct {
    var x: Double = _uninitialized()
        set(newValue) {
            willmutate()
            field = newValue
            didmutate()
        }
    var y: Double = _uninitialized()
        set(newValue) {
            willmutate()
            field = newValue
            didmutate()
        }

    constructor(x: Double = 0.0, y: Double = 0.0) {
        this.x = x
        this.y = y
    }

    …
}
```

The only workaround currently is to use the unsafe compiler flag `ProhibitMissedMustBeInitializedWhenThereIsNoPrimaryConstructor`, by specifying it in the `SkipUnit/Skip/skip.yml` file:

```yaml
    - block: 'tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>()'
      contents:
        - block: 'kotlinOptions'
          contents:
            #- 'suppressWarnings = true'
        - block: 'compilerOptions'
          contents:
            # https://youtrack.jetbrains.com/issue/KT-58589
            - 'freeCompilerArgs.add("-XXLanguage:-ProhibitMissedMustBeInitializedWhenThereIsNoPrimaryConstructor")'
```

However, this raises fairly menacing warnings in the gradle output:

```
GRADLE> > Task :SkipLib:compileDebugKotlin
GRADLE> w: ATTENTION!
GRADLE> This build uses unsafe internal compiler arguments:
GRADLE> 
GRADLE> -XXLanguage:-ProhibitMissedMustBeInitializedWhenThereIsNoPrimaryConstructor
GRADLE> 
GRADLE> This mode is not recommended for production use,
GRADLE> as no stability/compatibility guarantees are given on
GRADLE> compiler or generated code. Use it at your own risk!
```
